name: XenforoIntegration
main: net.ultimatemc.xenforointegration.XenforoIntegration
version: 1.0
description: Integrates Xenforo with Minecraft
commands:
   register:
     description: Register on Xenforo
     usage: '&c/register <email>'
   web:
     description: Base command for web interaction